title: ""
description: ""
url: "https://korolev-n.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"

author:
  name: "Имя"
  avatar: "/assets/images/avatar.jpg"
  bio: "bio"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/korolev-n"

social:
  type: Person
  name: "Имя"
  links:
    - "https://github.com/korolev-n"
    - "mailto:korolev.n@hotmail.com"

header:
  nav:
    - title: "Главная"
      url: /
    - title: "TIL"
      url: /til/
    - title: "Обо мне"
      url: /about/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-paginate

markdown: kramdown
highlighter: rouge

paginate: 5
paginate_path: "/page:num/"

collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true

theme: null
exclude: ["node_modules", "vendor", "Gemfile*", "README.md"]
